### ISSUE TITLE
no case clause matching: {:plugin_module_unloadable}

### ISSUE THREAD

**Issue by zjyang861** [deadtrickster/prometheus_rabbitmq_exporter#105]
accept
The following plugins have been configured:
  rabbitmq_management
  rabbitmq_management_agent
  rabbitmq_web_dispatch
Applying plugin configuration to rabbit@mq02...
** (CaseClauseError) no case clause matching: {:plugin_module_unloadable, 'prometheus_process_collector', {:error, :on_load_failure}}
    (rabbitmqctl) lib/rabbitmq/cli/plugins/plugins_helpers.ex:218: RabbitMQ.CLI.Plugins.Helpers.update_enabled_plugins/2
    (rabbitmqctl) lib/rabbitmq/cli/plugins/plugins_helpers.ex:115: RabbitMQ.CLI.Plugins.Helpers.update_enabled_plugins/4
    (rabbitmqctl) lib/rabbitmq/cli/plugins/commands/enable_command.ex:104: anonymous fn/6 in RabbitMQ.CLI.Plugins.Commands.EnableCommand.do_run/2
    (elixir) lib/stream.ex:1298: anonymous fn/2 in Stream.iterate/2
    (elixir) lib/stream.ex:1482: Stream.do_unfold/4
    (elixir) lib/stream.ex:1553: Enumerable.Stream.do_each/4
    (elixir) lib/stream.ex:933: Stream.do_enum_transform/7
    (elixir) lib/stream.ex:1553: Enumerable.Stream.do_each/4

**Comment by zjyang861** [comment]
I am getting this error when I enable the plugin, what is the problem?
