### ISSUE TITLE
plugin not work in  rabbitmq 3.7.12   Erlang 20.3.8.18

### ISSUE THREAD

**Issue by infoconsole** [deadtrickster/prometheus_rabbitmq_exporter#83]
There is an error in enabling plugins under rabbitmq 3.7.12, plugin version 3.7.9.1

```
[root@rabbit04 plugins]# rabbitmq-plugins enable prometheus_rabbitmq_exporter
Enabling plugins on node rabbit@rabbit04:
prometheus_rabbitmq_exporter
The following plugins have been configured:
  prometheus_rabbitmq_exporter
  rabbitmq_management
  rabbitmq_management_agent
  rabbitmq_peer_discovery_common
  rabbitmq_web_dispatch
Applying plugin configuration to rabbit@rabbit04...
** (CaseClauseError) no case clause matching: {:plugin_built_with_incompatible_erlang, 'accept'}
    (rabbitmqctl) lib/rabbitmq/cli/plugins/plugins_helpers.ex:218: RabbitMQ.CLI.Plugins.Helpers.update_enabled_plugins/2
    (rabbitmqctl) lib/rabbitmq/cli/plugins/plugins_helpers.ex:115: RabbitMQ.CLI.Plugins.Helpers.update_enabled_plugins/4
    (rabbitmqctl) lib/rabbitmq/cli/plugins/commands/enable_command.ex:104: anonymous fn/6 in RabbitMQ.CLI.Plugins.Commands.EnableCommand.do_run/2
    (elixir) lib/stream.ex:1298: anonymous fn/2 in Stream.iterate/2
    (elixir) lib/stream.ex:1482: Stream.do_unfold/4
    (elixir) lib/stream.ex:1553: Enumerable.Stream.do_each/4
    (elixir) lib/stream.ex:933: Stream.do_enum_transform/7
    (elixir) lib/stream.ex:1553: Enumerable.Stream.do_each/4
```

**Comment by deadtrickster** [comment]
Please rebuild https://github.com/deadtrickster/accept yourself: clone and run rebar3 archive
